In [4]:
import numpy as np

In [5]:
mylist = [1,2,3]

In [6]:
np.array(mylist)

array([1, 2, 3])

In [7]:
nested_list = [[1,2], [3,4], [5,6]]

In [8]:
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
np.arange(0, 11, 2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
np.zeros((4, 10), int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [15]:
np.ones((4,5),)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [47]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [17]:
np.linspace(0,10,21)

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,
        5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. ])

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(2)

array([0.46231131, 0.74621916])

In [20]:
np.random.rand(3,4)

array([[0.85088527, 0.17297131, 0.63469436, 0.71488659],
       [0.44265974, 0.95472411, 0.45685707, 0.95806723],
       [0.01691872, 0.30980711, 0.75254282, 0.32712578]])

In [21]:
np.random.randn(5,5)

array([[-0.40927111, -0.89909107, -0.03605658, -1.36416811,  0.07339673],
       [ 0.08673385, -0.45123355,  0.13218785,  0.79478231, -0.13881418],
       [ 0.33674038, -1.44456024, -1.70470429,  0.21184051, -0.30137603],
       [ 2.12185497,  0.89438662,  0.76015736,  0.71049611,  1.10826134],
       [-0.18017245,  0.17236519,  0.68422327,  0.0128717 ,  0.54848398]])

In [22]:
np.random.randint(1,100, 10)

array([28, 56, 83, 89, 41,  4, 53, 16,  4, 74])

In [23]:
np.random.randint(1,100,(3,4))

array([[16, 56,  6, 39],
       [ 5, 23, 81, 67],
       [84, 77, 94,  2]])

In [24]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [27]:
np.random.rand(4)

array([0.83244264, 0.21233911, 0.18182497, 0.18340451])

In [31]:
arr = np.arange(25)

In [29]:
ranarr = np.random.randint(0,50,10)

In [32]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
ranarr

array([11, 21, 43, 24, 48, 26, 41, 27, 15, 14])

In [34]:
arr.shape

(25,)

In [35]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
ranarr.max()

48

In [37]:
ranarr.argmax()

4

In [38]:
ranarr.min()

11

In [39]:
ranarr.argmin()

0

In [40]:
ranarr.dtype

dtype('int32')

In [43]:
arr.dtype

dtype('int32')