In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf

In [2]:
path_to_file = 'shakespeare.txt'

In [3]:
text = open(path_to_file, 'r').read()

In [4]:
text[4500:4800]

"converted are\n  From his low tract and look another way:\n    So thou, thy self out-going in thy noon:\n    Unlooked on diest unless thou get a son.\n\n\n                     8\n  Music to hear, why hear'st thou music sadly?\n  Sweets with sweets war not, joy delights in joy:\n  Why lov'st thou that which t"

In [5]:
vocab = sorted(set(text))

In [6]:
len(vocab)

84

In [7]:
for pair in enumerate(vocab):
    print(pair)

(0, '\n')
(1, ' ')
(2, '!')
(3, '"')
(4, '&')
(5, "'")
(6, '(')
(7, ')')
(8, ',')
(9, '-')
(10, '.')
(11, '0')
(12, '1')
(13, '2')
(14, '3')
(15, '4')
(16, '5')
(17, '6')
(18, '7')
(19, '8')
(20, '9')
(21, ':')
(22, ';')
(23, '<')
(24, '>')
(25, '?')
(26, 'A')
(27, 'B')
(28, 'C')
(29, 'D')
(30, 'E')
(31, 'F')
(32, 'G')
(33, 'H')
(34, 'I')
(35, 'J')
(36, 'K')
(37, 'L')
(38, 'M')
(39, 'N')
(40, 'O')
(41, 'P')
(42, 'Q')
(43, 'R')
(44, 'S')
(45, 'T')
(46, 'U')
(47, 'V')
(48, 'W')
(49, 'X')
(50, 'Y')
(51, 'Z')
(52, '[')
(53, ']')
(54, '_')
(55, '`')
(56, 'a')
(57, 'b')
(58, 'c')
(59, 'd')
(60, 'e')
(61, 'f')
(62, 'g')
(63, 'h')
(64, 'i')
(65, 'j')
(66, 'k')
(67, 'l')
(68, 'm')
(69, 'n')
(70, 'o')
(71, 'p')
(72, 'q')
(73, 'r')
(74, 's')
(75, 't')
(76, 'u')
(77, 'v')
(78, 'w')
(79, 'x')
(80, 'y')
(81, 'z')
(82, '|')
(83, '}')


In [8]:
char_to_ind = {char:ind for ind, char in enumerate(vocab)}

In [9]:
char_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [10]:
ind_to_char = np.array(vocab)

In [11]:
ind_to_char

array(['\n', ' ', '!', '"', '&', "'", '(', ')', ',', '-', '.', '0', '1',
       '2', '3', '4', '5', '6', '7', '8', '9', ':', ';', '<', '>', '?',
       'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       '[', ']', '_', '`', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
       'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v',
       'w', 'x', 'y', 'z', '|', '}'], dtype='<U1')

In [12]:
encoded_text = np.array([char_to_ind[c] for c in text])

In [13]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [14]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [15]:
line = 'From fairest creatures we desire increase'

In [16]:
len(line)

41

In [17]:
lines = '''From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease'''

In [18]:
len(lines)

130

In [19]:
seq_len = 120

In [20]:
total_num_seq = len(text) // (seq_len + 1)

In [21]:
total_num_seq

45005

In [22]:
char_dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [23]:
type(char_dataset)

tensorflow.python.data.ops.from_tensor_slices_op._TensorSliceDataset

In [24]:
# for item in char_dataset.take(500):
#     print(ind_to_char[item.numpy()])

In [25]:
sequences = char_dataset.batch(batch_size=seq_len+1, drop_remainder=True)

In [26]:
# for seq in sequences:
#     print(seq.numpy())

In [27]:
def create_seq_targets(seq):
    input_text = seq[:-1]
    target_text = seq[1:]
    return input_text, target_text

In [28]:
dataset = sequences.map(create_seq_targets)

In [29]:
for input_text, target_text in dataset.take(1):
    print(input_text.numpy())
    print("".join(ind_to_char[input_text.numpy()]))
    print()
    print(target_text.numpy())
    print("".join(ind_to_char[target_text.numpy()]))

[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75]

                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But

[ 1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0  1
  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74  1
 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45 63
 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74 60
  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75  1]
                     1
  From fairest creatures we desire increase,
  That thereby beauty's rose might never die,
  But 


In [30]:
batch_size = 128

In [31]:
buffer_size = 10000
dataset = dataset.shuffle(buffer_size=buffer_size).batch(batch_size=batch_size, drop_remainder=True)

In [32]:
dataset

<_BatchDataset element_spec=(TensorSpec(shape=(128, 120), dtype=tf.int32, name=None), TensorSpec(shape=(128, 120), dtype=tf.int32, name=None))>

In [33]:
sequences

<_BatchDataset element_spec=TensorSpec(shape=(121,), dtype=tf.int32, name=None)>

In [34]:
vocab_size = len(vocab)

In [35]:
vocab_size

84

In [36]:
embed_dim = 64

In [37]:
rnn_neurons = 1026

In [38]:
from tensorflow.keras.losses import sparse_categorical_crossentropy

In [39]:
help(sparse_categorical_crossentropy)

Help on function sparse_categorical_crossentropy in module keras.src.losses:

sparse_categorical_crossentropy(y_true, y_pred, from_logits=False, axis=-1, ignore_class=None)
    Computes the sparse categorical crossentropy loss.
    
    Standalone usage:
    
    >>> y_true = [1, 2]
    >>> y_pred = [[0.05, 0.95, 0], [0.1, 0.8, 0.1]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred)
    >>> assert loss.shape == (2,)
    >>> loss.numpy()
    array([0.0513, 2.303], dtype=float32)
    
    >>> y_true = [[[ 0,  2],
    ...            [-1, -1]],
    ...           [[ 0,  2],
    ...            [-1, -1]]]
    >>> y_pred = [[[[1.0, 0.0, 0.0], [0.0, 0.0, 1.0]],
    ...             [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]],
    ...           [[[1.0, 0.0, 0.0], [0.0, 0.5, 0.5]],
    ...            [[0.2, 0.5, 0.3], [0.0, 1.0, 0.0]]]]
    >>> loss = tf.keras.losses.sparse_categorical_crossentropy(
    ...   y_true, y_pred, ignore_class=-1)
    >>> loss.numpy()
    array([[[2

In [40]:
def sparse_cat_loss(y_true, y_pred):
    return sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [41]:
layers = tf.keras.layers

In [42]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = tf.keras.models.Sequential([
        layers.Embedding(vocab_size, embed_dim, batch_input_shape=(batch_size, None)),
        layers.GRU(rnn_neurons, return_sequences=True, stateful=True, recurrent_initializer='glorot_uniform'),
        layers.Dense(vocab_size),
    ])

    model.compile(optimizer='adam', loss=sparse_cat_loss)
    return model

In [43]:
model = create_model(vocab_size=vocab_size, embed_dim=embed_dim, rnn_neurons=rnn_neurons, batch_size=batch_size)

In [44]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM,Dense,Embedding,Dropout,GRU

In [45]:
# def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
#     model = Sequential()
#     model.add(Embedding(vocab_size, embed_dim,batch_input_shape=[batch_size, None]))
#     model.add(GRU(rnn_neurons,return_sequences=True,stateful=True,recurrent_initializer='glorot_uniform'))
#     # Final Dense Layer to Predict
#     model.add(Dense(vocab_size))
#     model.compile(optimizer='adam', loss=sparse_cat_loss) 
#     return model

In [46]:
# model = create_model(
#   vocab_size = vocab_size,
#   embed_dim=embed_dim,
#   rnn_neurons=rnn_neurons,
#   batch_size=batch_size)

In [47]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (128, None, 64)           5376      
                                                                 
 gru (GRU)                   (128, None, 1026)         3361176   
                                                                 
 dense (Dense)               (128, None, 84)           86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [48]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape)

(128, 120, 84)


In [49]:
example_batch_predictions[0]

<tf.Tensor: shape=(120, 84), dtype=float32, numpy=
array([[ 0.00359692,  0.00491967,  0.00057709, ...,  0.00090896,
        -0.00756292, -0.00149596],
       [-0.00192104,  0.00403598, -0.00299216, ..., -0.00203615,
        -0.00466292, -0.00123754],
       [-0.00469626, -0.00157854,  0.00072341, ..., -0.00065703,
         0.0023482 ,  0.00277515],
       ...,
       [ 0.00543924,  0.00690742, -0.00461551, ...,  0.0033547 ,
         0.00311006,  0.00502965],
       [ 0.00452722,  0.00249963, -0.00145936, ...,  0.00326443,
         0.00650464,  0.00205807],
       [ 0.005733  , -0.00159403, -0.00152334, ...,  0.00507656,
         0.00636812,  0.00164072]], dtype=float32)>

In [50]:
sample_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)

In [51]:
sample_indices

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[62],
       [ 5],
       [26],
       [50],
       [ 1],
       [43],
       [28],
       [47],
       [ 3],
       [79],
       [ 2],
       [24],
       [ 6],
       [56],
       [36],
       [38],
       [55],
       [17],
       [25],
       [13],
       [64],
       [38],
       [ 2],
       [20],
       [20],
       [57],
       [29],
       [13],
       [82],
       [ 3],
       [26],
       [40],
       [47],
       [69],
       [42],
       [52],
       [46],
       [ 9],
       [ 0],
       [83],
       [ 5],
       [74],
       [30],
       [71],
       [31],
       [56],
       [49],
       [43],
       [23],
       [36],
       [45],
       [12],
       [66],
       [29],
       [73],
       [14],
       [49],
       [32],
       [54],
       [23],
       [22],
       [ 8],
       [27],
       [ 3],
       [79],
       [35],
       [68],
       [ 8],
       [ 4],
       [62],
       [ 4],
       [81],
       [82],
   

In [52]:
sample_indices = tf.squeeze(sample_indices, axis=-1)

In [53]:
sample_indices

<tf.Tensor: shape=(120,), dtype=int64, numpy=
array([62,  5, 26, 50,  1, 43, 28, 47,  3, 79,  2, 24,  6, 56, 36, 38, 55,
       17, 25, 13, 64, 38,  2, 20, 20, 57, 29, 13, 82,  3, 26, 40, 47, 69,
       42, 52, 46,  9,  0, 83,  5, 74, 30, 71, 31, 56, 49, 43, 23, 36, 45,
       12, 66, 29, 73, 14, 49, 32, 54, 23, 22,  8, 27,  3, 79, 35, 68,  8,
        4, 62,  4, 81, 82, 44,  1, 37, 38, 83, 60, 78, 64, 31, 24, 53, 39,
       34, 50, 46, 57, 65, 82, 16,  2, 33, 34, 13, 72, 34, 73, 13, 11, 17,
       44, 23, 82, 30, 26, 83, 14, 42, 46, 45, 13, 23, 71, 82, 15, 27, 50,
       79], dtype=int64)>

In [54]:
ind_to_char[sample_indices]

array(['g', "'", 'A', 'Y', ' ', 'R', 'C', 'V', '"', 'x', '!', '>', '(',
       'a', 'K', 'M', '`', '6', '?', '2', 'i', 'M', '!', '9', '9', 'b',
       'D', '2', '|', '"', 'A', 'O', 'V', 'n', 'Q', '[', 'U', '-', '\n',
       '}', "'", 's', 'E', 'p', 'F', 'a', 'X', 'R', '<', 'K', 'T', '1',
       'k', 'D', 'r', '3', 'X', 'G', '_', '<', ';', ',', 'B', '"', 'x',
       'J', 'm', ',', '&', 'g', '&', 'z', '|', 'S', ' ', 'L', 'M', '}',
       'e', 'w', 'i', 'F', '>', ']', 'N', 'I', 'Y', 'U', 'b', 'j', '|',
       '5', '!', 'H', 'I', '2', 'q', 'I', 'r', '2', '0', '6', 'S', '<',
       '|', 'E', 'A', '}', '3', 'Q', 'U', 'T', '2', '<', 'p', '|', '4',
       'B', 'Y', 'x'], dtype='<U1')

In [55]:
epochs = 30

In [56]:
# model.fit(dataset, epochs=epochs)

# Evaluating the model

In [57]:
model = create_model(vocab_size=vocab_size, embed_dim=embed_dim, rnn_neurons=rnn_neurons, batch_size=1)

model.load_weights('shakespeare_gen.h5')

model.build(tf.TensorShape((1, None)))

In [58]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (1, None, 64)             5376      
                                                                 
 gru_1 (GRU)                 (1, None, 1026)           3361176   
                                                                 
 dense_1 (Dense)             (1, None, 84)             86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [64]:
def generate_text(model, start_seed, gen_size=500, temp=1.0):
    
    num_generate = gen_size
    
    input_eval = [char_to_ind[s] for s in start_seed]

    # print(input_eval)

    input_eval = tf.expand_dims(input_eval, axis=0)

    # print(input_eval)

    text_generated = []

    temperature = temp

    model.reset_states()

    for i in range(num_generate):
        predictions = model(input_eval)
        # print(predictions)
        predictions = tf.squeeze(predictions, axis=0)
        # print(predictions)
        predictions = predictions / temperature
        predicted_id = tf.random.categorical(predictions, num_samples=1)
        print(predicted_id)
        predicted_id = predicted_id[-1, 0].numpy()
        print(predicted_id)
        input_eval = tf.expand_dims([predicted_id], axis=0)
        text_generated.append(ind_to_char[predicted_id])
    
    return(start_seed + ''.join(text_generated))

In [65]:
print(generate_text(model, 'JULIET', gen_size=5))

tf.Tensor(
[[46]
 [28]
 [37]
 [49]
 [43]
 [28]], shape=(6, 1), dtype=int64)
28
tf.Tensor([[10]], shape=(1, 1), dtype=int64)
10
tf.Tensor([[1]], shape=(1, 1), dtype=int64)
1
tf.Tensor([[38]], shape=(1, 1), dtype=int64)
38
tf.Tensor([[80]], shape=(1, 1), dtype=int64)
80
JULIETC. My
