In [1]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
path_to_text ='shakespeare.txt'

In [3]:
text = open(path_to_text, 'r').read()

In [4]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [6]:
vocab = sorted(set(text))

In [7]:
vocab

['\n',
 ' ',
 '!',
 '"',
 '&',
 "'",
 '(',
 ')',
 ',',
 '-',
 '.',
 '0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 ':',
 ';',
 '<',
 '>',
 '?',
 'A',
 'B',
 'C',
 'D',
 'E',
 'F',
 'G',
 'H',
 'I',
 'J',
 'K',
 'L',
 'M',
 'N',
 'O',
 'P',
 'Q',
 'R',
 'S',
 'T',
 'U',
 'V',
 'W',
 'X',
 'Y',
 'Z',
 '[',
 ']',
 '_',
 '`',
 'a',
 'b',
 'c',
 'd',
 'e',
 'f',
 'g',
 'h',
 'i',
 'j',
 'k',
 'l',
 'm',
 'n',
 'o',
 'p',
 'q',
 'r',
 's',
 't',
 'u',
 'v',
 'w',
 'x',
 'y',
 'z',
 '|',
 '}']

In [8]:
text_to_ind = {char:ind for ind, char in enumerate(vocab)}

In [9]:
text_to_ind

{'\n': 0,
 ' ': 1,
 '!': 2,
 '"': 3,
 '&': 4,
 "'": 5,
 '(': 6,
 ')': 7,
 ',': 8,
 '-': 9,
 '.': 10,
 '0': 11,
 '1': 12,
 '2': 13,
 '3': 14,
 '4': 15,
 '5': 16,
 '6': 17,
 '7': 18,
 '8': 19,
 '9': 20,
 ':': 21,
 ';': 22,
 '<': 23,
 '>': 24,
 '?': 25,
 'A': 26,
 'B': 27,
 'C': 28,
 'D': 29,
 'E': 30,
 'F': 31,
 'G': 32,
 'H': 33,
 'I': 34,
 'J': 35,
 'K': 36,
 'L': 37,
 'M': 38,
 'N': 39,
 'O': 40,
 'P': 41,
 'Q': 42,
 'R': 43,
 'S': 44,
 'T': 45,
 'U': 46,
 'V': 47,
 'W': 48,
 'X': 49,
 'Y': 50,
 'Z': 51,
 '[': 52,
 ']': 53,
 '_': 54,
 '`': 55,
 'a': 56,
 'b': 57,
 'c': 58,
 'd': 59,
 'e': 60,
 'f': 61,
 'g': 62,
 'h': 63,
 'i': 64,
 'j': 65,
 'k': 66,
 'l': 67,
 'm': 68,
 'n': 69,
 'o': 70,
 'p': 71,
 'q': 72,
 'r': 73,
 's': 74,
 't': 75,
 'u': 76,
 'v': 77,
 'w': 78,
 'x': 79,
 'y': 80,
 'z': 81,
 '|': 82,
 '}': 83}

In [10]:
ind_to_text = np.array(vocab)

In [12]:
ind_to_text[12]

'1'

In [14]:
text_to_ind['1']

12

In [19]:
encoded_text = np.array([text_to_ind[c] for c in text])

In [20]:
encoded_text[:500]

array([ 0,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1, 12,  0,  1,  1, 31, 73, 70, 68,  1, 61, 56, 64,
       73, 60, 74, 75,  1, 58, 73, 60, 56, 75, 76, 73, 60, 74,  1, 78, 60,
        1, 59, 60, 74, 64, 73, 60,  1, 64, 69, 58, 73, 60, 56, 74, 60,  8,
        0,  1,  1, 45, 63, 56, 75,  1, 75, 63, 60, 73, 60, 57, 80,  1, 57,
       60, 56, 76, 75, 80,  5, 74,  1, 73, 70, 74, 60,  1, 68, 64, 62, 63,
       75,  1, 69, 60, 77, 60, 73,  1, 59, 64, 60,  8,  0,  1,  1, 27, 76,
       75,  1, 56, 74,  1, 75, 63, 60,  1, 73, 64, 71, 60, 73,  1, 74, 63,
       70, 76, 67, 59,  1, 57, 80,  1, 75, 64, 68, 60,  1, 59, 60, 58, 60,
       56, 74, 60,  8,  0,  1,  1, 33, 64, 74,  1, 75, 60, 69, 59, 60, 73,
        1, 63, 60, 64, 73,  1, 68, 64, 62, 63, 75,  1, 57, 60, 56, 73,  1,
       63, 64, 74,  1, 68, 60, 68, 70, 73, 80, 21,  0,  1,  1, 27, 76, 75,
        1, 75, 63, 70, 76,  1, 58, 70, 69, 75, 73, 56, 58, 75, 60, 59,  1,
       75, 70,  1, 75, 63

In [21]:
text[:500]

"\n                     1\n  From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease,\n  His tender heir might bear his memory:\n  But thou contracted to thine own bright eyes,\n  Feed'st thy light's flame with self-substantial fuel,\n  Making a famine where abundance lies,\n  Thy self thy foe, to thy sweet self too cruel:\n  Thou that art now the world's fresh ornament,\n  And only herald to the gaudy spring,\n  Within thine own bu"

In [22]:
line = 'From fairest creatures we desire increase'

In [23]:
len(line)

41

In [25]:
lines = "From fairest creatures we desire increase,\n  That thereby beauty's rose might never die,\n  But as the riper should by time decease"

In [26]:
len(lines)

130

In [27]:
seq_length = 120

In [30]:
total_num_sequences = len(text) // (seq_length+1)

In [31]:
total_num_sequences

45005

In [34]:
dataset = tf.data.Dataset.from_tensor_slices(encoded_text)

In [35]:
sequences = dataset.batch(batch_size=(seq_length+1), drop_remainder=True)

In [40]:
for seq in sequences.take(1):
    print(len(seq))
    print(seq)

121
tf.Tensor(
[ 0  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1  1 12  0
  1  1 31 73 70 68  1 61 56 64 73 60 74 75  1 58 73 60 56 75 76 73 60 74
  1 78 60  1 59 60 74 64 73 60  1 64 69 58 73 60 56 74 60  8  0  1  1 45
 63 56 75  1 75 63 60 73 60 57 80  1 57 60 56 76 75 80  5 74  1 73 70 74
 60  1 68 64 62 63 75  1 69 60 77 60 73  1 59 64 60  8  0  1  1 27 76 75
  1], shape=(121,), dtype=int32)


In [41]:
def create_seq_targets(seq):
    input_text = seq[:-1]
    output_text = seq[1:]
    return input_text, output_text

In [44]:
dataset = sequences.map(create_seq_targets)

In [45]:
buffer_size = 10000
batch_size = 128
dataset = dataset.shuffle(buffer_size=buffer_size, seed=101).batch(batch_size=batch_size, drop_remainder=True)

In [46]:
vocab_size = len(vocab)

In [47]:
vocab_size

84

In [49]:
embed_dim = 64
rnn_neurons = 1026

In [48]:
def sparse_cat_entropy(y_true, y_pred):
    return tf.keras.losses.sparse_categorical_crossentropy(y_true, y_pred, from_logits=True)

In [51]:
layers = tf.keras.layers

In [56]:
def create_model(vocab_size, embed_dim, rnn_neurons, batch_size):
    model = tf.keras.models.Sequential([
        layers.Embedding(input_dim=vocab_size, output_dim=embed_dim, batch_input_shape=(batch_size, None)),
        layers.GRU(rnn_neurons, recurrent_initializer='glorot_uniform', stateful=True, return_sequences=True),
        layers.Dense(vocab_size)
    ])
    model.compile(optimizer='adam', loss=sparse_cat_entropy)
    return model

In [57]:
model = create_model(vocab_size=vocab_size, embed_dim=embed_dim, rnn_neurons=rnn_neurons, batch_size=batch_size)

In [58]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (128, None, 64)           5376      
                                                                 
 gru_1 (GRU)                 (128, None, 1026)         3361176   
                                                                 
 dense_1 (Dense)             (128, None, 84)           86268     
                                                                 
Total params: 3452820 (13.17 MB)
Trainable params: 3452820 (13.17 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [60]:
for input, output in dataset.take(1):
    ex_batch_pred = model(input)
    print(ex_batch_pred.shape)
    print(ex_batch_pred)

(128, 120, 84)
tf.Tensor(
[[[-1.23389647e-03 -5.69363870e-03  2.30979826e-03 ... -1.00751373e-03
    2.48931069e-03 -2.19612173e-03]
  [-1.51493016e-03 -5.55417547e-03 -3.79760284e-03 ...  3.57460254e-03
   -3.66402185e-03 -5.34003833e-03]
  [ 4.56140470e-03 -1.00379833e-03 -5.13201579e-03 ...  1.76563603e-03
   -7.73050589e-04 -3.15097277e-03]
  ...
  [-2.65766401e-03 -2.20672810e-03  4.72464832e-03 ...  4.49626800e-03
   -2.06462154e-03 -4.52559395e-03]
  [-2.89121270e-03 -2.00090976e-03 -8.40285677e-04 ...  5.92498481e-03
   -5.14471112e-03 -4.97441273e-03]
  [-2.69973092e-03 -1.86900748e-03 -3.40820407e-03 ...  6.48890762e-03
   -6.89630397e-03 -4.52549756e-03]]

 [[ 3.35194939e-03 -5.36373677e-03 -2.25806609e-03 ... -1.27978425e-03
    8.75710510e-03  1.60032103e-03]
  [-1.39220199e-03 -8.14021844e-03  4.89543844e-03 ...  1.09475479e-03
    6.97899284e-03  5.13872039e-03]
  [-2.93406704e-03 -8.66814423e-03  5.99387195e-03 ...  2.49854580e-04
    6.75544282e-03  1.77878013e-03]
  .

In [62]:
sam_ind = tf.random.categorical(ex_batch_pred[0], num_samples=1)

In [63]:
sam_ind

<tf.Tensor: shape=(120, 1), dtype=int64, numpy=
array([[56],
       [32],
       [24],
       [78],
       [51],
       [71],
       [19],
       [34],
       [54],
       [39],
       [61],
       [40],
       [44],
       [40],
       [66],
       [26],
       [81],
       [28],
       [38],
       [ 3],
       [81],
       [54],
       [50],
       [54],
       [56],
       [ 0],
       [27],
       [13],
       [55],
       [43],
       [61],
       [ 2],
       [56],
       [60],
       [27],
       [66],
       [20],
       [ 5],
       [49],
       [67],
       [71],
       [39],
       [ 0],
       [80],
       [26],
       [65],
       [ 8],
       [74],
       [ 2],
       [64],
       [14],
       [20],
       [26],
       [ 9],
       [30],
       [62],
       [32],
       [70],
       [ 4],
       [ 1],
       [41],
       [72],
       [38],
       [52],
       [60],
       [57],
       [49],
       [23],
       [37],
       [ 1],
       [49],
       [59],
       [49],
   

In [64]:
sam_ind = tf.squeeze(sam_ind)

In [65]:
sam_ind

<tf.Tensor: shape=(120,), dtype=int64, numpy=
array([56, 32, 24, 78, 51, 71, 19, 34, 54, 39, 61, 40, 44, 40, 66, 26, 81,
       28, 38,  3, 81, 54, 50, 54, 56,  0, 27, 13, 55, 43, 61,  2, 56, 60,
       27, 66, 20,  5, 49, 67, 71, 39,  0, 80, 26, 65,  8, 74,  2, 64, 14,
       20, 26,  9, 30, 62, 32, 70,  4,  1, 41, 72, 38, 52, 60, 57, 49, 23,
       37,  1, 49, 59, 49, 14, 33, 70, 31, 54, 37, 72, 31, 34, 73, 15, 75,
       65, 81, 14, 56, 79, 14, 40, 65, 60, 59, 67, 63,  3, 42, 52, 32, 38,
        8, 48, 24, 43, 73, 55, 62, 81,  6, 40, 42, 22, 35, 39, 22, 23, 56,
       48], dtype=int64)>

In [66]:
ind_to_text[sam_ind]

array(['a', 'G', '>', 'w', 'Z', 'p', '8', 'I', '_', 'N', 'f', 'O', 'S',
       'O', 'k', 'A', 'z', 'C', 'M', '"', 'z', '_', 'Y', '_', 'a', '\n',
       'B', '2', '`', 'R', 'f', '!', 'a', 'e', 'B', 'k', '9', "'", 'X',
       'l', 'p', 'N', '\n', 'y', 'A', 'j', ',', 's', '!', 'i', '3', '9',
       'A', '-', 'E', 'g', 'G', 'o', '&', ' ', 'P', 'q', 'M', '[', 'e',
       'b', 'X', '<', 'L', ' ', 'X', 'd', 'X', '3', 'H', 'o', 'F', '_',
       'L', 'q', 'F', 'I', 'r', '4', 't', 'j', 'z', '3', 'a', 'x', '3',
       'O', 'j', 'e', 'd', 'l', 'h', '"', 'Q', '[', 'G', 'M', ',', 'W',
       '>', 'R', 'r', '`', 'g', 'z', '(', 'O', 'Q', ';', 'J', 'N', ';',
       '<', 'a', 'W'], dtype='<U1')